/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "../MCAL/RCC/rcc.h"
#include <stdio.h>
#include "../MCAL/GPIO/gpio.h"
const RCCConfig_t SystemClockConfig = {
.sysClkSource=HSI ,
.AHBPrescaler = NO_DIV ,
.APB1Prescaler= NO_DIV ,
.MCO_OutSrc = Out_HSI ,
.APB2Prescaler = NO_DIV
};
const PinConfig_t Pin = {
	.Pin =Pin_0,
	.Port =Port_B,
	.Mode=OUT_PUSH_PULL_10MHZ ,
	.Direction =OUTPUT,
	.State=SET
};
int main(void)
{
	vRCC_Init(&SystemClockConfig);
	GPIO_Init(&Pin) ;
	for (long long i=4 ; i>0 ; i--)
	{
		GPIO_TogglePin(&Pin);
	}
	for(;;);
}


